# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20160829_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'doença'},
        ),
    ]
