# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteractionChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title (Optional)', max_length=150, null=True)),
                ('description', models.CharField(blank=True, help_text='Description (Optional)', max_length=500, null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_drugs', models.ManyToManyField(to='drug.Drug')),
            ],
        ),
    ]
