# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druginteractionchecker',
            name='description',
        ),
    ]
