# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('action', models.CharField(max_length=125, verbose_name='action')),
            ],
            options={
                'verbose_name': 'drug',
            },
        ),
    ]
