# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': 'drug'},
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
