# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-10 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=750, null=True, verbose_name='description')),
                ('drugs', models.ManyToManyField(to='drug.Drug')),
            ],
        ),
    ]
