# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_checkerresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
